version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/roulette
    networks:
      app_network:
        ipv4_address: 192.168.1.2

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=roulette
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 192.168.1.3


volumes:
  db_data:


networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
