version: "3.8"

services:
  web:
    image: python:3.9-slim
    container_name: roulette_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.2
    depends_on:
      - database

  database:
    image: postgres:14
    container_name: roulette_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roulette
    networks:
      custom_network:
        ipv4_address: 192.168.1.3

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
