#removed version because it is now deprecated, according to an error message

services:
  web:
    container_name: roulette_web
    build: .
    ports:
      - "${APP_PORT}:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      app_network:
        ipv4_address: 192.168.1.2
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: roulette_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 192.168.1.3

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

